## Section A: Data Structures & Control Structures


### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.



In [1]:
list=[24,48,67,83,55]

In [2]:
list.append(10)
list

[24, 48, 67, 83, 55, 10]

In [3]:
list.extend([11,12])
list

[24, 48, 67, 83, 55, 10, 11, 12]

In [4]:
list.insert(2,25)
list

[24, 48, 25, 67, 83, 55, 10, 11, 12]

In [5]:
list.remove(67)
list

[24, 48, 25, 83, 55, 10, 11, 12]

In [6]:
list.pop(1)

48

In [7]:
list.clear()
list

[]

In [8]:
list=[24,48,67,83,55,24,42,24]

In [9]:
list.index(67)

2

In [10]:
list.count(24)

3

In [11]:
list.sort()
list

[24, 24, 24, 42, 48, 55, 67, 83]

In [12]:
list.reverse()
list

[83, 67, 55, 48, 42, 24, 24, 24]

### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.


In [13]:
tpl=('hari', 'siddiq', 'harshith')

In [14]:
tpl[1]='krishna'

TypeError: 'tuple' object does not support item assignment

In [15]:
#Changing of tuple shows the typeerror because  tuples are immutable, meaning their contents cannot be changed after creation

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.


In [16]:
set={1,2,3,4,2,4,5,6,7}
set

{1, 2, 3, 4, 5, 6, 7}

In [17]:
# It is designed in a way that it only stores unique values and delete duplicate values in the set automatically 

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [18]:
dict1={'name':"Hari",
      'age' :"23",
      'city':"bangaluru"
     }
dict1

{'name': 'Hari', 'age': '23', 'city': 'bangaluru'}

In [19]:
dict2={'age':"25"}

In [20]:
dict1.update(dict2)
dict1

{'name': 'Hari', 'age': '25', 'city': 'bangaluru'}

In [21]:
dict1['email']="hari123@gmail.com"

In [22]:
dict1

{'name': 'Hari',
 'age': '25',
 'city': 'bangaluru',
 'email': 'hari123@gmail.com'}

### 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.


In [24]:
vote=int(input("Enter the age of person: "))

Enter the age of person:  18


In [25]:
vote>=18

if vote>=18:
    print("Eligibal to vote")
    print("He/She is major")
else:
    print("Not eligibal to vot")
    print("He/She is minor")

Eligibal to vote
He/She is major


### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [26]:
mark=int(input("Enter the marks:"))

if mark>=90:
    print("A")
elif mark>=75 and mark<=89:
    print("B")
elif mark>=50 and mark<=74:
    print("C")
else :
    print("Fail")

Enter the marks: 65


C


### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [27]:
num=int(input("Enter the number:"))

num>0

if num>0:
    print("It is positive")
    if num%2==0:
        print("It is also even")
elif num<0:
    print("It's negative")
else:
    print("It's zero")

Enter the number: 18


It is positive
It is also even


### Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [28]:
import numpy as np

In [29]:
arr = np.array(5)

print(arr)

5


In [30]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [31]:
arr = np.array([[10,20,30],
               [40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [32]:
import random

In [33]:
arr=np.random.randint(1,101, size=(4,4))

print(arr)

[[ 3  4 28 43]
 [23 81 96 63]
 [26 37  3 60]
 [10 34 97 68]]


##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [34]:
import pandas as pd
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

df=pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [35]:
import pandas as pd
import numpy as np

In [36]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [25, 30, 35, 28, 22, 40, 32, 29, 27, 30],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Chicago', 'Miami', 'Seattle', 'Los Angeles'],
    'Salary': [60000, 75000, 90000, 62000, 55000, np.nan, 80000, 68000, 72000, 75000]
}
df = pd.DataFrame(data)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [38]:
df.describe()

Age        Salary
count  10.000000      9.000000
mean   29.800000  70777.777778
std     5.072803  10848.707040
min    22.000000  55000.000000
25%    27.250000  62000.000000
50%    29.500000  72000.000000
75%    31.500000  75000.000000
max    40.000000  90000.000000

In [45]:
print(df[['Name', 'City']])

       Name         City
0     Alice     New York
1       Bob  Los Angeles
2   Charlie      Chicago
3     David      Houston
4       Eve      Phoenix
5     Frank     New York
6     Grace      Chicago
7     Heidi        Miami
8      Ivan      Seattle
9      Judy  Los Angeles
10      Bob  Los Angeles


In [40]:
df_no_city = df.drop(columns=['City'])
print(df_no_city)

      Name  Age   Salary
0    Alice   25  60000.0
1      Bob   30  75000.0
2  Charlie   35  90000.0
3    David   28  62000.0
4      Eve   22  55000.0
5    Frank   40      NaN
6    Grace   32  80000.0
7    Heidi   29  68000.0
8     Ivan   27  72000.0
9     Judy   30  75000.0


In [46]:
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, 
                    inplace=True)
print(df)

       Name  Age         City        Salary
0     Alice   25     New York  60000.000000
1       Bob   30  Los Angeles  75000.000000
2   Charlie   35      Chicago  90000.000000
3     David   28      Houston  62000.000000
4       Eve   22      Phoenix  55000.000000
5     Frank   40     New York  70777.777778
6     Grace   32      Chicago  80000.000000
7     Heidi   29        Miami  68000.000000
8      Ivan   27      Seattle  72000.000000
9      Judy   30  Los Angeles  75000.000000
10      Bob   30  Los Angeles  75000.000000


C:\Users\harik\AppData\Local\Temp\ipykernel_2076\2934386217.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary,


In [42]:
duplicate_row = pd.DataFrame([['Bob', 30, 'Los Angeles', 75000]], columns=df.columns)
df = pd.concat([df, duplicate_row], ignore_index=True)
print(df)

       Name  Age         City        Salary
0     Alice   25     New York  60000.000000
1       Bob   30  Los Angeles  75000.000000
2   Charlie   35      Chicago  90000.000000
3     David   28      Houston  62000.000000
4       Eve   22      Phoenix  55000.000000
5     Frank   40     New York  70777.777778
6     Grace   32      Chicago  80000.000000
7     Heidi   29        Miami  68000.000000
8      Ivan   27      Seattle  72000.000000
9      Judy   30  Los Angeles  75000.000000
10      Bob   30  Los Angeles  75000.000000


In [43]:
df_no_duplicates = df.drop_duplicates()
print("DataFrame after removing duplicate rows:")
print(df_no_duplicates)

DataFrame after removing duplicate rows:
      Name  Age         City        Salary
0    Alice   25     New York  60000.000000
1      Bob   30  Los Angeles  75000.000000
2  Charlie   35      Chicago  90000.000000
3    David   28      Houston  62000.000000
4      Eve   22      Phoenix  55000.000000
5    Frank   40     New York  70777.777778
6    Grace   32      Chicago  80000.000000
7    Heidi   29        Miami  68000.000000
8     Ivan   27      Seattle  72000.000000
9     Judy   30  Los Angeles  75000.000000
